"""
Multi-Language Keyboard Layouts: English (US), French (AZERTY), Arabic (101).
"""
from evdev import ecodes as e

ENGLISH_US_LAYOUT = [
    [
        ("`", "~", e.KEY_GRAVE, "char", 1),
        ("1", "!", e.KEY_1, "char", 1),
        ("2", "@", e.KEY_2, "char", 1),
        ("3", "#", e.KEY_3, "char", 1),
        ("4", "$", e.KEY_4, "char", 1),
        ("5", "%", e.KEY_5, "char", 1),
        ("6", "^", e.KEY_6, "char", 1),
        ("7", "&", e.KEY_7, "char", 1),
        ("8", "*", e.KEY_8, "char", 1),
        ("9", "(", e.KEY_9, "char", 1),
        ("0", ")", e.KEY_0, "char", 1),
        ("-", "_", e.KEY_MINUS, "char", 1),
        ("=", "+", e.KEY_EQUAL, "char", 1),
        ("⌫", "⌫", e.KEY_BACKSPACE, "backspace", 1.6),
    ],
    [
        ("Tab", "Tab", e.KEY_TAB, "tab", 1.3),
        ("q", "Q", e.KEY_Q, "char", 1),
        ("w", "W", e.KEY_W, "char", 1),
        ("e", "E", e.KEY_E, "char", 1),
        ("r", "R", e.KEY_R, "char", 1),
        ("t", "T", e.KEY_T, "char", 1),
        ("y", "Y", e.KEY_Y, "char", 1),
        ("u", "U", e.KEY_U, "char", 1),
        ("i", "I", e.KEY_I, "char", 1),
        ("o", "O", e.KEY_O, "char", 1),
        ("p", "P", e.KEY_P, "char", 1),
        ("[", "{", e.KEY_LEFTBRACE, "char", 1),
        ("]", "}", e.KEY_RIGHTBRACE, "char", 1),
        ("\\", "|", e.KEY_BACKSLASH, "char", 1.1),
    ],
    [
        ("Caps", "Caps", e.KEY_CAPSLOCK, "caps", 1.5),
        ("a", "A", e.KEY_A, "char", 1),
        ("s", "S", e.KEY_S, "char", 1),
        ("d", "D", e.KEY_D, "char", 1),
        ("f", "F", e.KEY_F, "char", 1),
        ("g", "G", e.KEY_G, "char", 1),
        ("h", "H", e.KEY_H, "char", 1),
        ("j", "J", e.KEY_J, "char", 1),
        ("k", "K", e.KEY_K, "char", 1),
        ("l", "L", e.KEY_L, "char", 1),
        (";", ":", e.KEY_SEMICOLON, "char", 1),
        ("'", '"', e.KEY_APOSTROPHE, "char", 1),
        ("↵ Enter", "↵ Enter", e.KEY_ENTER, "enter", 1.8),
    ],
    [
        ("⇧ Shift", "⇧ Shift", e.KEY_LEFTSHIFT, "shift", 1.8),
        ("z", "Z", e.KEY_Z, "char", 1),
        ("x", "X", e.KEY_X, "char", 1),
        ("c", "C", e.KEY_C, "char", 1),
        ("v", "V", e.KEY_V, "char", 1),
        ("b", "B", e.KEY_B, "char", 1),
        ("n", "N", e.KEY_N, "char", 1),
        ("m", "M", e.KEY_M, "char", 1),
        (",", "<", e.KEY_COMMA, "char", 1),
        (".", ">", e.KEY_DOT, "char", 1),
        ("/", "?", e.KEY_SLASH, "char", 1),
        ("⇧ Shift", "⇧ Shift", e.KEY_RIGHTSHIFT, "shift", 1.8),
    ],
    [
        ("Space", "Space", e.KEY_SPACE, "space", 6.0)
    ]
]

FRENCH_AZERTY_LAYOUT = [
    [
        ("²", "~", e.KEY_GRAVE, "char", 1),
        ("&", "1", e.KEY_1, "char", 1),
        ("é", "2", e.KEY_2, "char", 1),
        ('"', "3", e.KEY_3, "char", 1),
        ("'", "4", e.KEY_4, "char", 1),
        ("(", "5", e.KEY_5, "char", 1),
        ("-", "6", e.KEY_MINUS, "char", 1),
        ("è", "7", e.KEY_7, "char", 1),
        ("_", "8", e.KEY_8, "char", 1),
        ("ç", "9", e.KEY_9, "char", 1),
        ("à", "0", e.KEY_0, "char", 1),
        (")", "°", e.KEY_EQUAL, "char", 1),
        ("=", "+", e.KEY_BACKSLASH, "char", 1),
        ("⌫", "⌫", e.KEY_BACKSPACE, "backspace", 1.6),
    ],
    [
        ("Tab", "Tab", e.KEY_TAB, "tab", 1.3),
        ("a", "A", e.KEY_A, "char", 1),
        ("z", "Z", e.KEY_Z, "char", 1),
        ("e", "E", e.KEY_E, "char", 1),
        ("r", "R", e.KEY_R, "char", 1),
        ("t", "T", e.KEY_T, "char", 1),
        ("y", "Y", e.KEY_Y, "char", 1),
        ("u", "U", e.KEY_U, "char", 1),
        ("i", "I", e.KEY_I, "char", 1),
        ("o", "O", e.KEY_O, "char", 1),
        ("p", "P", e.KEY_P, "char", 1),
        ("^", "¨", e.KEY_LEFTBRACE, "char", 1),
        ("$", "£", e.KEY_RIGHTBRACE, "char", 1),
        ("*", "µ", e.KEY_BACKSLASH, "char", 1.1),
    ],
    [
        ("Caps", "Caps", e.KEY_CAPSLOCK, "caps", 1.5),
        ("q", "Q", e.KEY_Q, "char", 1),
        ("s", "S", e.KEY_S, "char", 1),
        ("d", "D", e.KEY_D, "char", 1),
        ("f", "F", e.KEY_F, "char", 1),
        ("g", "G", e.KEY_G, "char", 1),
        ("h", "H", e.KEY_H, "char", 1),
        ("j", "J", e.KEY_J, "char", 1),
        ("k", "K", e.KEY_K, "char", 1),
        ("l", "L", e.KEY_L, "char", 1),
        ("m", "M", e.KEY_M, "char", 1),
        ("ù", "%", e.KEY_APOSTROPHE, "char", 1),
        ("↵ Enter", "↵ Enter", e.KEY_ENTER, "enter", 1.8),
    ],
    [
        ("⇧ Shift", "⇧ Shift", e.KEY_LEFTSHIFT, "shift", 1.8),
        ("w", "W", e.KEY_W, "char", 1),
        ("x", "X", e.KEY_X, "char", 1),
        ("c", "C", e.KEY_C, "char", 1),
        ("v", "V", e.KEY_V, "char", 1),
        ("b", "B", e.KEY_B, "char", 1),
        ("n", "N", e.KEY_N, "char", 1),
        (",", "?", e.KEY_COMMA, "char", 1),
        (";", ".", e.KEY_SEMICOLON, "char", 1),
        (":", "/", e.KEY_SLASH, "char", 1),
        ("!", "§", e.KEY_SLASH, "char", 1),
        ("⇧ Shift", "⇧ Shift", e.KEY_RIGHTSHIFT, "shift", 1.8),
    ],
    [
        ("Space", "Space", e.KEY_SPACE, "space", 6.0)
    ]
]

ARABIC_LAYOUT = [
    [
        ("ذ", "ّ", e.KEY_GRAVE, "char", 1),
        ("1", "!", e.KEY_1, "char", 1),
        ("2", "@", e.KEY_2, "char", 1),
        ("3", "#", e.KEY_3, "char", 1),
        ("4", "$", e.KEY_4, "char", 1),
        ("5", "%", e.KEY_5, "char", 1),
        ("6", "^", e.KEY_6, "char", 1),
        ("7", "&", e.KEY_7, "char", 1),
        ("8", "*", e.KEY_8, "char", 1),
        ("9", ")", e.KEY_9, "char", 1),
        ("0", "(", e.KEY_0, "char", 1),
        ("-", "_", e.KEY_MINUS, "char", 1),
        ("=", "+", e.KEY_EQUAL, "char", 1),
        ("⌫", "⌫", e.KEY_BACKSPACE, "backspace", 1.6),
    ],
    [
        ("Tab", "Tab", e.KEY_TAB, "tab", 1.3),
        ("ض", "َ", e.KEY_Q, "char", 1),
        ("ص", "ً", e.KEY_W, "char", 1),
        ("ث", "ُ", e.KEY_E, "char", 1),
        ("ق", "ٌ", e.KEY_R, "char", 1),
        ("ف", "لإ", e.KEY_T, "char", 1),
        ("غ", "إ", e.KEY_Y, "char", 1),
        ("ع", "`", e.KEY_U, "char", 1),
        ("ه", "÷", e.KEY_I, "char", 1),
        ("خ", "×", e.KEY_O, "char", 1),
        ("ح", "؛", e.KEY_P, "char", 1),
        ("ج", "<", e.KEY_LEFTBRACE, "char", 1),
        ("د", ">", e.KEY_RIGHTBRACE, "char", 1),
        ("\\", "|", e.KEY_BACKSLASH, "char", 1.1),
    ],
    [
        ("Caps", "Caps", e.KEY_CAPSLOCK, "caps", 1.5),
        ("ش", "ِ", e.KEY_A, "char", 1),
        ("س", "ٍ", e.KEY_S, "char", 1),
        ("ي", "]", e.KEY_D, "char", 1),
        ("ب", "[", e.KEY_F, "char", 1),
        ("ل", "لأ", e.KEY_G, "char", 1),
        ("ا", "أ", e.KEY_H, "char", 1),
        ("ت", "ـ", e.KEY_J, "char", 1),
        ("ن", "،", e.KEY_K, "char", 1),
        ("م", "/", e.KEY_L, "char", 1),
        ("ك", ":", e.KEY_SEMICOLON, "char", 1),
        ("ط", '"', e.KEY_APOSTROPHE, "char", 1),
        ("↵ Enter", "↵ Enter", e.KEY_ENTER, "enter", 1.8),
    ],
    [
        ("⇧ Shift", "⇧ Shift", e.KEY_LEFTSHIFT, "shift", 1.8),
        ("ئ", "~", e.KEY_Z, "char", 1),
        ("ء", "ْ", e.KEY_X, "char", 1),
        ("ؤ", "}", e.KEY_C, "char", 1),
        ("ر", "{", e.KEY_V, "char", 1),
        ("لا", "لآ", e.KEY_B, "char", 1),
        ("ى", "آ", e.KEY_N, "char", 1),
        ("ة", "'", e.KEY_M, "char", 1),
        ("و", ",", e.KEY_COMMA, "char", 1),
        ("ز", ".", e.KEY_DOT, "char", 1),
        ("ظ", "؟", e.KEY_SLASH, "char", 1),
        ("⇧ Shift", "⇧ Shift", e.KEY_RIGHTSHIFT, "shift", 1.8),
    ],
    [
        ("Space", "Space", e.KEY_SPACE, "space", 6.0)
    ]
]

LANGUAGE_REGISTRY = {
    "en": {"name": "English (US)", "badge": "[EN]", "layout": ENGLISH_US_LAYOUT},
    "fr": {"name": "Français (AZERTY)", "badge": "[FR]", "layout": FRENCH_AZERTY_LAYOUT},
    "ar": {"name": "العربية (Arabic)", "badge": "[AR]", "layout": ARABIC_LAYOUT},
}
